In [1]:
import torch

### Tensors

In [3]:
torch.empty(5, 3)

tensor([[ 0.0000e+00,  0.0000e+00,  8.1275e-43],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-1.2617e+14,  3.5593e-43,  0.0000e+00],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-1.4229e+14,  3.5593e-43,  0.0000e+00]])

In [4]:
torch.rand(5, 3)

tensor([[ 0.2817,  0.3400,  0.6412],
        [ 0.9926,  0.9145,  0.6741],
        [ 0.0920,  0.9176,  0.4202],
        [ 0.1703,  0.2061,  0.7541],
        [ 0.2110,  0.9696,  0.0953]])

In [5]:
torch.zeros(5, 3, dtype=torch.int8)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]], dtype=torch.int8)

#### Tensor from data

In [6]:
torch.tensor([5.5, 3])

tensor([ 5.5000,  3.0000])

#### Tensor from an existing tensor

In [7]:
x = torch.zeros(5, 3, dtype=torch.int)
print(x)
x = x.new_ones(5, 3)      # new_* methods take in sizes
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]], dtype=torch.int32)
tensor([[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]], dtype=torch.int32)


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[-0.3652,  0.8713, -2.5085],
        [-0.3860, -0.2656,  0.3954],
        [ 0.4002, -1.1943, -0.6128],
        [-0.6800, -0.4484,  1.7059],
        [ 0.7844,  0.1834, -1.5288]])


In [9]:
x.shape

torch.Size([5, 3])

### Operations

In [10]:
y = torch.rand(5, 3)
print(y)

tensor([[ 0.3063,  0.4801,  0.2200],
        [ 0.4202,  0.0394,  0.0326],
        [ 0.9233,  0.2896,  0.9461],
        [ 0.7173,  0.5356,  0.9618],
        [ 0.0910,  0.4035,  0.3896]])


In [11]:
print(x + y)

tensor([[-0.0589,  1.3514, -2.2885],
        [ 0.0342, -0.2261,  0.4280],
        [ 1.3235, -0.9047,  0.3333],
        [ 0.0373,  0.0872,  2.6677],
        [ 0.8755,  0.5869, -1.1392]])


In [12]:
print(torch.add(x, y))

tensor([[-0.0589,  1.3514, -2.2885],
        [ 0.0342, -0.2261,  0.4280],
        [ 1.3235, -0.9047,  0.3333],
        [ 0.0373,  0.0872,  2.6677],
        [ 0.8755,  0.5869, -1.1392]])


#### Output tensor argument

In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0589,  1.3514, -2.2885],
        [ 0.0342, -0.2261,  0.4280],
        [ 1.3235, -0.9047,  0.3333],
        [ 0.0373,  0.0872,  2.6677],
        [ 0.8755,  0.5869, -1.1392]])


#### In-place

In [14]:
y.add_(x)
print(y)

tensor([[-0.0589,  1.3514, -2.2885],
        [ 0.0342, -0.2261,  0.4280],
        [ 1.3235, -0.9047,  0.3333],
        [ 0.0373,  0.0872,  2.6677],
        [ 0.8755,  0.5869, -1.1392]])


#### Any operation that mutates a tensor in-place is post-fixed with an _. 
For example: x.copy\_(y), x.t\_(), will change x.

#### Resizing

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


#### Tensor to Python numbers

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8259])
-0.8259193897247314


100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described [here](https://pytorch.org/docs/stable/torch.html).

### NumPy Bridge

In [17]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [18]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [19]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[ 2.  2.  2.  2.  2.]


#### NumPy to Tensors

In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)
